export const routes = {
  home: '/',
  dashboard: '/dashboard',
  bookings: '/bookings',
  baseCalendar: '/calendar',
  calendarWithoutOrId: '/calendar/:view',
  calendar: '/calendar/:view',
  bookingDetails: '/bookings/:caseId',
  newBookingRequest: '/bookings/new',
  cases: '/cases',
  patientCases: '/cases/patient/:patientId',
  caseDetails: '/cases/:caseId',
  caseDetailsTabs: ['details', 'opStandards'],
  caseEdit: '/cases/:caseId/edit',
  schedule: '/schedule/:view',
  defaultSchedule: '/schedule/week',
  auditTrails: '/audittrail',
  systemConfiguration: '/systemconfiguration',
  contractsList: '/contracts',
  contractDetails: '/contracts/:contractId',
  editContract: '/contracts/:contractId/edit',
  newContract: '/contracts/new',
  OPStandardDetails: '/contracts/:contractId/opstandards/:opStandardId',
  addNewOPStandard: '/contracts/:contractId/opstandards/new',
  addNewContractOPStandard: '/contracts/new/opstandards/new',
  editOPStandard: '/contracts/:contractId/opstandards/:opStandardId/edit',
  anesthesiologistsSchedule: '/anesthesiologistsschedule/:view/:orId',
  defaultAnesthesiologistsSchedule: '/anesthesiologistsschedule/day/all',
  anesthesiologistOPStandardList: '/anesthesiologistopstandards',
  anesthesiologistOPStandardDetails: '/anesthesiologistopstandards/:anesthesiologistopstandardId',
  editAnesthesiologistOPStandard: '/anesthesiologistopstandards/:anesthesiologistopstandardId/edit',
  newVersionAnesthesiologistOPStandard: '/anesthesiologistopstandards/:anesthesiologistopstandardId/new-version',
  addNewAnesthesiologistOPStandard: '/anesthesiologistopstandards/new',
  logManagement: '/logs',
  usersList: '/users',
  userDetails: '/users/:userId',
  userEdit: '/users/:userId/edit',
  newUser: '/users/new',
  rolesList: '/roles',
  roleDetails: '/roles/:roleId',
  roleEdit: '/roles/:roleId/edit',
  newRole: '/roles/new',
  patientsList: '/patients',
  patientDetails: '/patients/:patientId',
  editPatient: '/patients/:patientId/edit',
  orList: '/ormanagement',
  orDetails: '/ormanagement/:orId',
  anagraphics: '/anagraphics/:anagraphicType',
  newOr: '/ormanagement/newOr',
  explorer: '/explorer',
  universalConfigurations: '/universalconfigurations/:tenantId/urConfigs',

  surplusSection: '/surplus/',
  pcMaterials: '/pc-materials/:tab',
  pcMaterialsBase: '/pc-materials',
  login: '/auth/login',
  forgotPassword: '/auth/forgot-password',
  verifyEmail: '/auth/verify-email',
  resetPassword: '/auth/reset-password',

  mapPatientDetails: (id: string) => `/patients/${id}`,
  mapUserDetails: (id: string) => `/users/${id}`,
  mapUserEdit: (id: string) => `/users/${id}/edit`,
  mapRoleDetails: (id: string) => `/roles/${id}`,
  mapRoleEdit: (id: string) => `/roles/${id}/edit`,
  mapOrDetails: (id: string) => `/ormanagement/${id}`,
  mapPatientEdit: (id: string) => `/patients/${id}/edit`,
  mapContractDetails: (id: string) => `/contracts/${id}`,
  mapContractEdit: (id: string) => `/contracts/${id}/edit`,
  mapCreateOpStandard: (contractId: string) => `/contracts/${contractId}/opstandards/new`,
  mapAnesthesiologistOPStandardDetails: (id: string) => `/anesthesiologistopstandards/${id}`,
  mapAnesthesiologistOPStandardEdit: (id: string) => `/anesthesiologistopstandards/${id}/edit`,
  mapAnesthesiologistOPStandardNewVersion: (id: string) => `/anesthesiologistopstandards/${id}/new-version`,
  mapCaseDetails: (id: string) => `/cases/${id}`,
  mapUniversalConfigurations: (tenantId: string) => `/universalconfigurations/${tenantId}/urConfigs`,
  mapPcMaterials: (tab?: string) => `/pc-materials/${tab}`,
  mapAnagraphics: (anagraphicType: string) => `/anagraphics/${anagraphicType}`,
}

export const contractManagementLocations = {
  contractDetails: 'contract/contractdetails',
  editContract: 'contract/editcontract',
  addNewContract: 'contract/newcontract',
}
