services:

  playwright:
    container_name: playwright
    image: mcr.microsoft.com/playwright
    entrypoint: sh
    working_dir: /app
    volumes:
      - ./tests:/app/tests
      - ./playwright.env:/app/playwright.env
      - ./playwright.config.ts:/app/playwright.config.ts
      - ./.env.${NODE_ENV}:/app/.env
      - ./node_modules:/app/node_modules
      - ./constants:/app/constants
      - ./constantsjs:/app/constantsjs
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command:
      - -c
      - |
        npx playwright install --with-deps chromium;
        npx playwright test;
    depends_on:
      ascos-anagraphics:
        condition: service_healthy
      ascos-auth:
        condition: service_healthy
      ascos-billing:
        condition: service_healthy
      ascos-bucket:
        condition: service_healthy
      ascos-contracts:
        condition: service_healthy
      ascos-logs:
        condition: service_healthy
      ascos-notifications:
        condition: service_healthy
      ascos-ormanagement:
        condition: service_healthy 
      ascos-patient-anagraphics:   
        condition: service_healthy    
      ascos-roles:  
        condition: service_healthy
      ascos-scheduling-cases:
        condition: service_healthy
      ascos-system-configuration:
        condition: service_healthy
      ascos-tenants:
        condition: service_healthy
      ascos-users:
        condition: service_healthy
      init:
        condition: service_completed_successfully
    networks:
      - smambu

networks:
  smambu: