export const PDF_THEME_DETAILS = {
  STROKE_COLOR: '#aaaaaa',
  FILL_COLOR: '#444444',
  FONT_BOLD: 'Helvetica-Bold',
  FONT_NORMAL: 'Helvetica',
  FONT_SIZE_BIGGER: 25,
  FONT_SIZE_BIG: 20,
  FONT_SIZE_MEDIUM: 15,
  FONT_SIZE_NORMAL: 10,
  FONT_SIZE_MEDIUM_SMALL: 8,
  FONT_SIZE_SMALL: 6,
}
