export const GLOBAL_ACTION = {
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  ADD_TOAST: 'ADD_TOAST',
  REMOVE_TOAST: 'REMOVE_TOAST',
  SET_SELECTED_DATE: 'SET_SELECTED_DATE',
  SET_OR_IDS: 'SET_OR_IDS',
  TOOGLE_DRAWER_STATUS: 'TOOGLE_DRAWER_STATUS',
  SET_APP_CURRENCY_SYMBOLS: 'SET_APP_CURRENCY_SYMBOLS',
  TOGGLE_FULL_SCREEN: 'TOGGLE_FULL_SCREEN',
  TOGGLE_ENABLED_FULL_SCREEN: 'TOGGLE_ENABLED_FULL_SCREEN',
}

export const FILTERS_ACTION = {
  SET_SECTION_FILTER: 'SET_SECTION_FILTER',
  RESET_SECTION: 'RESET_SECTION',
}

export const TENANTS_ACTION = {
  SET_DATA: 'SET_DATA',
  SET_TENANT: 'SET_TENANT',
  SET_TENANT_PROPS: 'SET_TENANT_PROPS',
}

export const AUTH_ACTION = {
  LOGIN_REQUEST: 'AUTH_ACTION/LOGIN_REQUEST',
  LOGIN_WITHOUT_TENANT_SUCCESS: 'AUTH_ACTION/LOGIN_WITHOUT_TENANT_SUCCESS',
  LOGIN_WITH_TENANT_SUCCESS: 'AUTH_ACTION/LOGIN_WITH_TENANT_SUCCESS',
  LOGIN_ERROR: 'AUTH_ACTION/LOGIN_ERROR',
  GET_CURRENT_USER: 'AUTH_ACTION/GET_CURRENT_USER',
  GET_CURRENT_USER_SUCCESS: 'AUTH_ACTION/GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_ERROR: 'AUTH_ACTION/GET_CURRENT_USER_ERROR',
  LOG_OUT: 'AUTH_ACTION/LOG_OUT',
  RESET_PASSWORD_REQUEST: 'AUTH_ACTION/RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'AUTH_ACTION/RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_ERROR: 'AUTH_ACTION/RESET_PASSWORD_ERROR',
  FORGOT_PASSWORD_REQUEST: 'AUTH_ACTION/FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'AUTH_ACTION/FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_ERROR: 'AUTH_ACTION/FORGOT_PASSWORD_ERROR',
  VERIFY_EMAIL_REQUEST: 'AUTH_ACTION/VERIFY_EMAIL_REQUEST',
  VERIFY_EMAIL_SUCCESS: 'AUTH_ACTION/VERIFY_EMAIL_SUCCESS',
  VERIFY_EMAIL_ERROR: 'AUTH_ACTION/VERIFY_EMAIL_ERROR',
  GET_PERMISSIONS_SUCCESS: 'AUTH_ACTION/GET_PERMISSIONS_SUCCESS',
}

export const LANG_ACTION = {
  SET_LANG: 'SET_LANG',
}

export const CASES_ACTION = {
  SET_CASE: 'CASES_ACTION/SET_CASE',
  SET_CASES: 'CASES_ACTION/SET_CASES',
}

export const LIMITED_CASES_ACTION = {
  SET_CASE: 'LIMITED_CASES_ACTION/SET_CASE',
  SET_CASES: 'LIMITED_CASES_ACTION/SET_CASES',
}

export const ROLES_ACTION = {
  GET_ROLES_SUCCESS: 'ROLES_ACTION/GET_ROLES_SUCCESS',
}

export const SCHEDULING_ACTION = {
  SET_LOCKED_WEEK: 'SET_LOCKED_WEEK',
  SET_CASE_BACKUP: 'SET_CASE_BACKUP',
  RESET_BACKUPS: 'RESET_BACKUPS',
  SET_CASES_BACKUP: 'SET_CASES_BACKUP',
}

export const OPERATING_ROOMS_ACTION = {
  SET_OPERATING_ROOMS: 'SET_OPERATING_ROOMS',
  SET_OPERATING_ROOM: 'SET_OPERATING_ROOM',
}

export const OR_SCHEDULING_ACTION = {
  SET_OR_SCHEDULES: 'SET_OR_SCHEDULES',
  SET_EDITED_OR_SCHEDULES: 'SET_EDITED_OR_SCHEDULES',
  SET_OR_SCHEDULE_EDITED: 'SET_OR_SCHEDULE_EDITED',
  ADD_ANESTHESIOLOGIST_TO_ROOM: 'ADD_ANESTHESIOLOGIST_TO_ROOM',
  REMOVE_ANESTHESIOLOGIST_FROM_ROOM: 'REMOVE_ANESTHESIOLOGIST_FROM_ROOM',
}

export const USER_ACTION = {
  GET_USERS_REQUEST: 'USER_ACTION/GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'USER_ACTION/GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'USER_ACTION/GET_USERS_ERROR',
  GET_USER_DETAIL_REQUEST: 'USER_ACTION/GET_USER_DETAIL_REQUEST',
  GET_USER_DETAIL_SUCCESS: 'USER_ACTION/GET_USER_DETAIL_SUCCESS',
  GET_USER_DETAIL_ERROR: 'USER_ACTION/GET_USER_DETAIL_ERROR',
  CREATE_USER_REQUEST: 'USER_ACTION/CREATE_USER_REQUEST',
  CREATE_USER_SUCCESS: 'USER_ACTION/CREATE_USER_SUCCESS',
  CREATE_USER_ERROR: 'USER_ACTION/CREATE_USER_ERROR',
  UPDATE_USER_REQUEST: 'USER_ACTION/UPDATE_USER_REQUEST',
  UPDATE_USER_SUCCESS: 'USER_ACTION/UPDATE_USER_SUCCESS',
  UPDATE_USER_ERROR: 'USER_ACTION/UPDATE_USER_ERROR',
  REQUEST_RESET_USER_PASSWORD_REQUEST: 'USER_ACTION/RESET_USER_PASSWORD_REQUEST',
  REQUEST_RESET_USER_PASSWORD_SUCCESS: 'USER_ACTION/RESET_USER_PASSWORD_SUCCESS',
  REQUEST_RESET_USER_PASSWORD_ERROR: 'USER_ACTION/RESET_USER_PASSWORD_ERROR',
}

export const CONFIG_ACTION = {
  SET_CONFIGS: 'SET_CONFIGS',
  SET_CONFIG: 'SET_CONFIG',
}

export const CONTRACT_ACTION = {
  SET_CONTRACTS: 'SET_CONTRACTS',
}

export const DRAFT_CONTRACT_ACTION = {
  SET_DRAFT_CONTRACT: 'SET_DRAFT_CONTRACT',
  ADD_DRAFT_CONTRACT_OPSTANDARD: 'ADD_DRAFT_CONTRACT_OPSTANDARD',
  RESET_DRAFT_CONTRACT: 'RESET_DRAFT_CONTRACT',
}

export const ANESTHESIOLOGISTS_SCHEDULE_ACTION = {
  SET_ANESTHESIOLOGISTS_SCHEDULE: 'SET_ANESTHESIOLOGISTS_SCHEDULE',
  CLEAR: 'CLEAR',
}

export const MATERIALS_DATABASE_ACTION = {
  SET_VERSION: 'SET_VERSION',
}

export const EXPLORER_ACTION = {
  SET_EXPLORER_FILTERS: 'SET_EXPLORER_FILTERS',
}

export const DYNAMIC_DATA_CONFIGS = {
  SET_CONTRACTS_DD: 'SET_CONTRACTS_DD',
  SET_OPSTANDARDS_DD: 'SET_OPSTANDARDS_DD',
  SET_CASES_DD: 'SET_CASES_DD',
  SET_ANAGRAPHICS_DD: 'SET_ANAGRAPHICS_DD',
  SET_CAPABILITIES_DD: 'SET_CAPABILITIES_DD',
  SET_ALL_DYNAMIC_DATA: 'SET_ALL_DYNAMIC_DATA'
}
