import { Capabilities } from '../enums'
import { Role } from '../types'

export const getFirstRolePayload = (tenantId: string): Omit<Role, 'tenantId' | 'userCount' | 'id'> => ({
  name: `admin-${tenantId}`,
  scope: 'ALL_DATA',
  domain_scopes: {
    USERS: 'ALL_DATA',
    DOCTORS: 'ALL_DATA',
    ANESTHESIOLOGISTS: 'ALL_DATA',
    ROLES: 'ALL_DATA',
    USER_TYPE: 'ALL_DATA',
    PATIENTS: 'ALL_DATA',
    SYSTEM: 'ALL_DATA',
    CONTRACTS: 'ALL_DATA',
    DOCTORS_OP_STANDARD: 'ALL_DATA',
    ANESTHESIOLOGIST_OP_STANDARD: 'ALL_DATA',
    BOOKING: 'ALL_DATA',
    CASES: 'ALL_DATA',
    CALENDAR: 'ALL_DATA',
    NOTES: 'ALL_DATA',
    TIMESTAMPS: 'ALL_DATA',
    COST_ESTIMATE: 'ALL_DATA',
    RECEIPT: 'ALL_DATA',
    BILLS: 'ALL_DATA',
    OR_MANAGEMENT: 'ALL_DATA',
    AUDIT_TRAIL: 'ALL_DATA',
    LOGS: 'ALL_DATA',
    MATERIALS_DATABASE: 'ALL_DATA',
    STERILE_GOODS: 'ALL_DATA',
    OPS_CATALOGUE: 'ALL_DATA',
    EBM: 'ALL_DATA',
    GOA: 'ALL_DATA',
    DASHBOARD: 'ALL_DATA',
    DOCUMENTS: 'ALL_DATA',
  },
  capabilities: [
    Capabilities.P_USERS_VIEW,
    Capabilities.P_USERS_EDIT,
    Capabilities.P_USERS_CREATE,
    Capabilities.P_DOCTORS_VIEW,
    Capabilities.P_ANESTHESIOLOGISTS_VIEW,
    Capabilities.P_ROLES_VIEW,
    Capabilities.P_ROLES_EDIT,
    Capabilities.P_ROLES_DELETE,
    Capabilities.P_ROLES_CREATE,
    Capabilities.P_PATIENTS_EDIT,
    Capabilities.P_TIMERANGE_EDIT,
    Capabilities.P_FILE_UPLOAD_EDIT,
    Capabilities.P_PRICE_PER_POINT_VALUE_EDIT,
    Capabilities.P_VAT_EDIT,
    Capabilities.P_CONTRACT_DEFAULT_PRICES_VIEW,
    Capabilities.P_CONTRACT_DEFAULT_PRICES_EDIT,
    Capabilities.P_DEFAULT_SUBJECT_AREAS_EDIT,
    Capabilities.P_INVOICE_NUMBERS_EDIT,
    Capabilities.P_CASE_NUMBERS_EDIT,
    Capabilities.P_PC_MATERIALS_NUMBERS_EDIT,
    Capabilities.P_PATIENT_NUMBERS_EDIT,
    Capabilities.P_DEBTOR_NUMBERS_EDIT,
    Capabilities.P_SUPPLIER_CODES_EDIT,
    Capabilities.P_COUNT_CONTROL_EDIT,
    Capabilities.P_INVOICE_GENERAL_DATA_EDIT,
    Capabilities.P_REVENUE_ACCOUNT_EDIT,
    Capabilities.P_ENVIRONMENT_CONFIGS_EDIT,
    Capabilities.P_CONTRACTS_VIEW,
    Capabilities.P_CONTRACTS_EDIT,
    Capabilities.P_CONTRACTS_CREATE,
    Capabilities.P_CONTRACTS_DELETE,
    Capabilities.P_D_OPSTANDARD_VIEW,
    Capabilities.P_D_OPSTANDARD_NAMES_VIEW,
    Capabilities.P_D_OPSTANDARD_EDIT,
    Capabilities.P_D_OPSTANDARD_DELETE,
    Capabilities.P_D_OPSTANDARD_CREATE,
    Capabilities.P_D_OPSTANDARD_REQUESTCHANGE,
    Capabilities.P_A_OPSTANDARD_VIEW,
    Capabilities.P_A_OPSTANDARD_NAMES_VIEW,
    Capabilities.P_A_OPSTANDARD_CREATE,
    Capabilities.P_A_OPSTANDARD_DELETE,
    Capabilities.P_A_OPSTANDARD_EDIT,
    Capabilities.P_BOOKINGS_CREATE,
    Capabilities.P_BOOKING_PATIENT_DETAILS_EDIT,
    Capabilities.P_BOOKINGS_SCHEDULE,
    Capabilities.P_BOOKINGS_REJECT,
    Capabilities.P_BOOKINGS_HOLD,
    Capabilities.P_BOOKINGS_VIEW,
    Capabilities.P_SCHEDULE_NOTES_VIEW,
    Capabilities.P_SCHEDULE_NOTES_EDIT,
    Capabilities.P_CASES_VIEW,
    Capabilities.P_CASES_STATUS_VIEW,
    Capabilities.P_CASES_DATABASE_ID_VIEW,
    Capabilities.P_CASES_CHECKIN_VIEW,
    Capabilities.P_CASES_CHECKIN_EDIT,
    Capabilities.P_CASES_BOOKING_INFO_VIEW,
    Capabilities.P_CASES_BOOKING_INFO_EDIT,
    Capabilities.P_CASES_SURGERY_INFO_VIEW,
    Capabilities.P_CASES_SURGERY_INFO_EDIT,
    Capabilities.P_SURGERY_CODES_VIEW,
    Capabilities.P_SURGERY_CODES_EDIT,
    Capabilities.P_CASES_BILLING_DETAILS_EDIT,
    Capabilities.P_CASES_PREOP_DOCUMENTATION_VIEW,
    Capabilities.P_CASES_PREOP_DOCUMENTATION_EDIT,
    Capabilities.P_CASES_ANESTHESIA_DOCUMENTATION_VIEW,
    Capabilities.P_CASES_ANESTHESIA_DOCUMENTATION_EDIT,
    Capabilities.P_CASES_ANESTHESIOLOGIST_ASSIGN,
    Capabilities.P_CASE_ANESTHESIOLOGIST_ASSIGN_SELF,
    Capabilities.P_CASES_INTRAOP_DOCUMENTATION_VIEW,
    Capabilities.P_CASES_INTRAOP_DOCUMENTATION_EDIT,
    Capabilities.P_CASES_POSTOP_DOCUMENTATION_VIEW,
    Capabilities.P_CASES_POSTOP_DOCUMENTATION_EDIT,
    Capabilities.P_CASES_CHECKOUT_VIEW,
    Capabilities.P_CASES_CHECKOUT_EDIT,
    Capabilities.P_CASES_EXPORT,
    Capabilities.P_CASES_DURATION_EDIT,
    Capabilities.P_PC_MATERIALS_VIEW,
    Capabilities.P_PC_MATERIALS_EXPORT,
    Capabilities.V_PREOP_TAB,
    Capabilities.V_ANESTHESIA_TAB,
    Capabilities.V_INTRAOP_TAB,
    Capabilities.V_POSTOP_TAB,
    Capabilities.V_BILLING_CODES,
    Capabilities.V_BILLING_CONTACTS,
    Capabilities.V_CASES_LIST,
    Capabilities.V_ALL_COLUMNS,
    Capabilities.V_PATIENTS_COLUMNS,
    Capabilities.V_STATUS_COLUMNS,
    Capabilities.V_BOOKING_INFO_COLUMNS,
    Capabilities.V_DOCTOR_COLUMNS,
    Capabilities.V_BILLING_COLUMNS,
    Capabilities.P_CASES_REVIEW,
    Capabilities.P_CALENDAR_VIEW,
    Capabilities.V_ALL_CALENDAR,
    Capabilities.V_DAILY_CALENDAR,
    Capabilities.V_WEEKLY_CALENDAR,
    Capabilities.V_MONTHLY_CALENDAR,
    Capabilities.V_ALL_ROOMS_CALENDAR,
    Capabilities.V_ALL_BOOKINGS,
    Capabilities.V_ASSIGNED_BOOKINGS,
    Capabilities.V_PATIENT_STATUS,
    Capabilities.V_CASE_STATUS,
    Capabilities.V_INTRAOP_PHASES,
    Capabilities.P_CALENDAR_NOTES_VIEW,
    Capabilities.P_CALENDAR_NOTES_EDIT,
    Capabilities.P_CALENDAR_PREOP_NOTES_VIEW,
    Capabilities.P_CALENDAR_PREOP_NOTES_EDIT,
    Capabilities.P_CALENDAR_POSTOP_NOTES_VIEW,
    Capabilities.P_CALENDAR_POSTOP_NOTES_EDIT,
    Capabilities.P_BOOKING_NOTES_VIEW,
    Capabilities.P_BOOKING_NOTES_EDIT,
    Capabilities.P_PREOP_NOTES_VIEW,
    Capabilities.P_PREOP_NOTES_EDIT,
    Capabilities.P_INTRAOP_NOTES_VIEW,
    Capabilities.P_INTRAOP_NOTES_EDIT,
    Capabilities.P_POSTOP_NOTES_VIEW,
    Capabilities.P_POSTOP_NOTES_EDIT,
    Capabilities.P_SURGERY_NOTES_VIEW,
    Capabilities.P_SURGERY_NOTES_EDIT,
    Capabilities.P_CHECKIN_TIMESTAMP_SET,
    Capabilities.P_CHECKIN_TIMESTAMP_VIEW,
    Capabilities.P_CHECKIN_TIMESTAMP_EDIT,
    Capabilities.P_CHECKOUT_TIMESTAMP_SET,
    Capabilities.P_CHECKOUT_TIMESTAMP_VIEW,
    Capabilities.P_CHECKOUT_TIMESTAMP_EDIT,
    Capabilities.P_PREOP_TIMESTAMP_SET,
    Capabilities.P_PREOP_TIMESTAMP_VIEW,
    Capabilities.P_PREOP_TIMESTAMP_EDIT,
    Capabilities.P_ANESTHESIA_TIMESTAMP_SET,
    Capabilities.P_ANESTHESIA_TIMESTAMP_VIEW,
    Capabilities.P_ANESTHESIA_TIMESTAMP_EDIT,
    Capabilities.P_PATIENT_TIMESTAMP_SET,
    Capabilities.P_PATIENT_TIMESTAMP_VIEW,
    Capabilities.P_PATIENT_TIMESTAMP_EDIT,
    Capabilities.P_SURGERY_TIMESTAMP_SET,
    Capabilities.P_SURGERY_TIMESTAMP_VIEW,
    Capabilities.P_SURGERY_TIMESTAMP_EDIT,
    Capabilities.P_POSTOP_TIMESTAMP_SET,
    Capabilities.P_POSTOP_TIMESTAMP_VIEW,
    Capabilities.P_POSTOP_TIMESTAMP_EDIT,
    Capabilities.P_COST_ESTIMATE_CREATE,
    Capabilities.P_COST_ESTIMATE_VIEW,
    Capabilities.P_COST_ESTIMATE_DOWNLOAD,
    Capabilities.P_RECEIPT_VIEW,
    Capabilities.P_RECEIPT_CREATE,
    Capabilities.P_RECEIPT_DOWNLOAD,
    Capabilities.P_BILLS_EDIT,
    Capabilities.P_BILLS_VIEW,
    Capabilities.P_BILLS_EXPORT,
    Capabilities.P_BILLS_DOWNLOAD,
    Capabilities.P_BILLS_PRESCRIBED,
    Capabilities.P_BILLS_CANCEL,
    Capabilities.P_BILLS_POST,
    Capabilities.P_BILLS_PAID,
    Capabilities.V_CANCELLED_BILLS,
    Capabilities.V_POSTED_BILLS,
    Capabilities.P_ANESTHESIOLOGIST_SCHEDULE_VIEW,
    Capabilities.P_ANESTHESIOLOGIST_SCHEDULE_EDIT,
    Capabilities.P_OR_CREATE,
    Capabilities.P_OR_VIEW,
    Capabilities.P_OR_EDIT,
    Capabilities.P_OR_DELETE,
    Capabilities.P_AUDITTRAIL_CREATE,
    Capabilities.P_AUDITTRAIL_DELETE,
    Capabilities.P_AUDITTRAIL_EDIT,
    Capabilities.P_AUDITTRAIL_VIEW,
    Capabilities.P_LOGS_CREATE,
    Capabilities.P_LOGS_DELETE,
    Capabilities.P_LOGS_EDIT,
    Capabilities.P_LOGS_VIEW,
    Capabilities.P_MATERIALS_DATABASE_NAMES_VIEW,
    Capabilities.P_MATERIALS_DATABASE_VIEW,
    Capabilities.P_MATERIALS_DATABASE_EDIT,
    Capabilities.P_MATERIALS_DATABASE_DELETE,
    Capabilities.P_MATERIALS_DATABASE_UPLOAD,
    Capabilities.P_MATERIALS_DATABASE_EXPORT,
    Capabilities.P_STERILE_GOODS_NAMES_VIEW,
    Capabilities.P_STERILE_GOODS_VIEW,
    Capabilities.P_STERILE_GOODS_EDIT,
    Capabilities.P_STERILE_GOODS_DELETE,
    Capabilities.P_STERILE_GOODS_UPLOAD,
    Capabilities.P_STERILE_GOODS_EXPORT,
    Capabilities.P_OPS_CATALOGUE_VIEW,
    Capabilities.P_OPS_CATALOGUE_EDIT,
    Capabilities.P_OPS_CATALOGUE_DELETE,
    Capabilities.P_OPS_CATALOGUE_UPLOAD,
    Capabilities.P_OPS_CATALOGUE_EXPORT,
    Capabilities.P_EBM_VIEW,
    Capabilities.P_EBM_EDIT,
    Capabilities.P_EBM_DELETE,
    Capabilities.P_EBM_UPLOAD,
    Capabilities.P_EBM_EXPORT,
    Capabilities.P_GOA_VIEW,
    Capabilities.P_GOA_EDIT,
    Capabilities.P_GOA_DELETE,
    Capabilities.P_GOA_UPLOAD,
    Capabilities.P_GOA_EXPORT,
    Capabilities.P_DASHBOARD_VIEW,
    Capabilities.P_DOCUMENTS_VIEW,
    Capabilities.P_DOCUMENTS_UPLOAD,
    Capabilities.P_DOCUMENTS_DOWNLOAD,
    Capabilities.P_CHECKIN_DOCUMENTS_VIEW,
    Capabilities.P_CHECKIN_DOCUMENTS_UPLOAD,
    Capabilities.P_CHECKIN_DOCUMENTS_DOWNLOAD,
    Capabilities.P_CHECKOUT_DOCUMENTS_VIEW,
    Capabilities.P_CHECKOUT_DOCUMENTS_UPLOAD,
    Capabilities.P_CHECKOUT_DOCUMENTS_DOWNLOAD,
    Capabilities.P_INTRAOP_DOCUMENTS_VIEW,
    Capabilities.P_INTRAOP_DOCUMENTS_UPLOAD,
    Capabilities.P_INTRAOP_DOCUMENTS_DOWNLOAD,
    Capabilities.P_BILLS_GENERATE,
    Capabilities.P_CASES_EDIT,
    Capabilities.P_PATIENTS_VIEW,
    Capabilities.P_CASES_BILLING_VIEW,
    Capabilities.P_CASES_BILLING_DETAILS_VIEW,
    Capabilities.P_USERS_ACTIVATE,
    Capabilities.P_EXPLORER_VIEW,
  ]
})
