export enum AuditAction {
  CREATED = 'CREATED',
  EDITED = 'EDITED',
  REMOVED = 'REMOVED',
}

export enum EntityType {
  ANAGRAPHIC = 'ANAGRAPHIC',
  CASE = 'CASE',
  CONTRACT = 'CONTRACT',
  USER = 'USER',
  CREDENTIAL = 'CREDENTIAL',
  OPSTANDARD = 'OPSTANDARD',
  OPERATING_ROOM = 'OPERATING_ROOM',
  ANESTHESIOLOGIST_OPSTANDARD = 'ANESTHESIOLOGIST_OPSTANDARD',
  PATIENT = 'PATIENT',
  BILL = 'BILL',
  CASEBILL = 'CASEBILL',
  ROLE = 'ROLE',
  SYSTEM_CONFIGURATION = 'SYSTEM_CONFIGURATION',
  INVOICE = 'INVOICE',
  CASE_BILLING_SNAPSHOT = 'SNAPSHOT',
  SAMMEL_CHECKPOINT = 'SAMMEL_CHECKPOINT',
  SCHEDULE_NOTE = 'SCHEDULE_NOTE',
  PRESCRIPTION = 'PRESCRIPTION',
}
