export const backendConfiguration = () => ({
  jwt: {
    privateKey: process.env.JWT_PRIVATE_KEY,
    options: { expiresIn: '1w' },
  },
  mongodb_uri_anagraphics: process.env.MONGODB_URI_ANAGRAPHICS,
  mongodb_uri_bucket: process.env.MONGODB_URI_BUCKET,
  mongodb_uri_tenants: process.env.MONGODB_URI_TENANTS,
  mongodb_uri_contracts: process.env.MONGODB_URI_CONTRACTS,
  mongodb_uri_logs: process.env.MONGODB_URI_LOGS,
  mongodb_uri_ormanagement: process.env.MONGODB_URI_ORMANAGEMENT,
  mongodb_uri_patient_anagraphics: process.env.MONGODB_URI_PATIENT_ANAGRAPHICS,
  mongodb_uri_roles: process.env.MONGODB_URI_ROLES,
  mongodb_uri_scheduling_cases: process.env.MONGODB_URI_SCHEDULING_CASES,
  mongodb_uri_system_configuration: process.env.MONGODB_URI_SYSTEM_CONFIGURATION,
  mongodb_uri_users: process.env.MONGODB_URI_USERS,
  mongodb_uri_billing: process.env.MONGODB_URI_BILLING,
  mongodb_uri_notifications: process.env.MONGODB_URI_NOTIFICATIONS,
  mongodb_uri_ur: process.env.MONGODB_URI_UR,
  domain_url: process.env.DOMAIN,
  appUrl: process.env.APP_URL,
  sendgridKey: process.env.SEND_GRID_KEY,
  sendgridEmail: process.env.SEND_GRID_EMAIL,
})
