export const HTTP_URLS_LABELS = {
  AUTH_API_URL: 'AUTH_API_URL',
  USER_API_URL: 'USER_API_URL',
  ROLE_API_URL: 'ROLE_API_URL',
  CONTRACT_API_URL: 'CONTRACT_API_URL',
  ANAGRAPHICS_API_URL: 'ANAGRAPHICS_API_URL',
  SCHEDULING_CASES_API_URL: 'SCHEDULING_CASES_API_URL',
  SYSTEM_CONFIGURATION_API_URL: 'SYSTEM_CONFIGURATION_API_URL',
  OR_MANAGEMENT_API_URL: 'OR_MANAGEMENT_API_URL',
  PATIENTS_API_URL: 'PATIENTS_API_URL',
  BUCKET_API_URL: 'BUCKET_API_URL',
  LOG_API_URL: 'LOG_API_URL',
  BILLING_API_URL: 'BILLING_API_URL',
  NOTIFICATIONS_API_URL: 'NOTIFICATIONS_API_URL',
  TENANTS_API_URL: 'TENANTS_API_URL',
  UR_API_URL: 'UR_API_URL',
}

export type tHttpUrlsLabels = keyof typeof HTTP_URLS_LABELS

export const getHttpUrls = (env: any): Record<tHttpUrlsLabels, string> => {
  const BACKEND_PROTOCOL = env.VITE_BACKEND_PROTOCOL || 'http'

  const AUTH_PORT = env.VITE_AUTH_PORT || 8010
  const AUTH_SERVICE_HOST = env.VITE_AUTH_SERVICE_HOST || 'localhost'
  const AUTH_API_URL = `${BACKEND_PROTOCOL}://${AUTH_SERVICE_HOST}:${AUTH_PORT}/api/auth`

  const USER_PORT = env.VITE_USER_PORT || 8020
  const USER_SERVICE_HOST = env.VITE_USER_SERVICE_HOST || 'localhost'
  const USER_API_URL = `${BACKEND_PROTOCOL}://${USER_SERVICE_HOST}:${USER_PORT}/api/user`

  const ROLE_PORT = env.VITE_ROLE_PORT || 8030
  const ROLE_SERVICE_HOST = env.VITE_ROLE_SERVICE_HOST || 'localhost'
  const ROLE_API_URL = `${BACKEND_PROTOCOL}://${ROLE_SERVICE_HOST}:${ROLE_PORT}/api/role`

  const CONTRACT_PORT = env.VITE_CONTRACT_PORT || 8040
  const CONTRACT_SERVICE_HOST = env.VITE_CONTRACT_SERVICE_HOST || 'localhost'
  const CONTRACT_API_URL = `${BACKEND_PROTOCOL}://${CONTRACT_SERVICE_HOST}:${CONTRACT_PORT}/api/contract`

  const ANAGRAPHICS_PORT = env.VITE_ANAGRAPHICS_PORT || 8050
  const ANAGRAPHICS_SERVICE_HOST = env.VITE_ANAGRAPHICS_SERVICE_HOST || 'localhost'
  const ANAGRAPHICS_API_URL = `${BACKEND_PROTOCOL}://${ANAGRAPHICS_SERVICE_HOST}:${ANAGRAPHICS_PORT}/api/anagraphics`

  const SCHEDULING_CASES_PORT = env.VITE_SCHEDULING_CASES_PORT || 8060
  const SCHEDULING_CASES_SERVICE_HOST = env.VITE_SCHEDULING_CASES_SERVICE_HOST || 'localhost'
  const SCHEDULING_CASES_API_URL = `${BACKEND_PROTOCOL}://${SCHEDULING_CASES_SERVICE_HOST}:${SCHEDULING_CASES_PORT}/api/schedulingcases`

  const BUCKET_PORT = env.VITE_BUCKET_SERVICE_PORT || 8070
  const BUCKET_SERVICE_HOST = env.VITE_BUCKET_SERVICE_HOST || 'localhost'
  const BUCKET_API_URL = `${BACKEND_PROTOCOL}://${BUCKET_SERVICE_HOST}:${BUCKET_PORT}/api/bucket`

  const SYSTEM_CONFIGURATION_PORT = env.VITE_SYSTEM_CONFIGURATION_PORT || 8080
  const SYSTEM_CONFIGURATION_SERVICE_HOST = env.VITE_SYSTEM_CONFIGURATION_SERVICE_HOST || 'localhost'
  const SYSTEM_CONFIGURATION_API_URL = `${BACKEND_PROTOCOL}://${SYSTEM_CONFIGURATION_SERVICE_HOST}:${SYSTEM_CONFIGURATION_PORT}/api/system-configuration/app`

  const LOGS_PORT = env.VITE_LOGS_PORT || 8090
  const LOGS_SERVICE_HOST = env.VITE_LOGS_SERVICE_HOST || 'localhost'
  const LOG_API_URL = `${BACKEND_PROTOCOL}://${LOGS_SERVICE_HOST}:${LOGS_PORT}/api/log`

  const PATIENTS_PORT = env.VITE_PATIENTS_ANAGRAPHICS_SERVICE_PORT || 8110
  const PATIENTS_SERVICE_HOST = env.VITE_PATIENTS_ANAGRAPHICS_SERVICE_HOST || 'localhost'
  const PATIENTS_API_URL = `${BACKEND_PROTOCOL}://${PATIENTS_SERVICE_HOST}:${PATIENTS_PORT}/api/patientAnagraphics`

  const OR_MANAGEMENT_PORT = env.VITE_OR_MANAGEMENT_PORT || 8120
  const OR_MANAGEMENT_SERVICE_HOST = env.VITE_OR_MANAGEMENT_SERVICE_HOST || 'localhost'
  const OR_MANAGEMENT_API_URL = `${BACKEND_PROTOCOL}://${OR_MANAGEMENT_SERVICE_HOST}:${OR_MANAGEMENT_PORT}/api/or-management`

  const BILLING_PORT = env.VITE_BILLING_PORT || 8130
  const BILLING_SERVICE_HOST = env.VITE_BILLING_SERVICE_HOST || 'localhost'
  const BILLING_API_URL = `${BACKEND_PROTOCOL}://${BILLING_SERVICE_HOST}:${BILLING_PORT}/api/billing`

  const NOTIFICATIONS_PORT = env.VITE_NOTIFICATIONS_PORT || 8140
  const NOTIFICATIONS_SERVICE_HOST = env.VITE_NOTIFICATIONS_SERVICE_HOST || 'localhost'
  const NOTIFICATIONS_API_URL = `${BACKEND_PROTOCOL}://${NOTIFICATIONS_SERVICE_HOST}:${NOTIFICATIONS_PORT}/api/notifications`

  const TENANTS_PORT = env.VITE_TENANTS_PORT || 8150
  const TENANTS_SERVICE_HOST = env.VITE_TENANTS_SERVICE_HOST || 'localhost'
  const TENANTS_API_URL = `${BACKEND_PROTOCOL}://${TENANTS_SERVICE_HOST}:${TENANTS_PORT}/api/tenant`

  const UR_PORT = env.VITE_UR_PORT || 8160
  const UR_SERVICE_HOST = env.VITE_UR_SERVICE_HOST || 'localhost'
  const UR_API_URL = `${BACKEND_PROTOCOL}://${UR_SERVICE_HOST}:${UR_PORT}/api/ur`

  return ({
    AUTH_API_URL,
    USER_API_URL,
    ROLE_API_URL,
    ANAGRAPHICS_API_URL,
    CONTRACT_API_URL,
    SCHEDULING_CASES_API_URL,
    SYSTEM_CONFIGURATION_API_URL,
    OR_MANAGEMENT_API_URL,
    PATIENTS_API_URL,
    BUCKET_API_URL,
    LOG_API_URL,
    BILLING_API_URL,
    NOTIFICATIONS_API_URL,
    TENANTS_API_URL,
    UR_API_URL,
  })
}
